services:
  selenium:
    container_name: selenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    image: selenium/standalone-chrome:latest 
    environment:
      - SE_NODE_SESSION_TIMEOUT=1800
    ports:
      - 4444:4444
    shm_size: 2gb
  bumber:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      selenium:
        condition: service_healthy